version: '3'
volumes:
  node_modules:

services:
  test_deployments_dev:
    container_name: test_deployments_dev
    build:
      context: .
    working_dir: /extension
    command: cextrun -d --no-rich-logging
    volumes: 
      - .:/extension
      - node_modules:/extension/node_modules
    env_file:
      - .test_deployments_dev.env

  test_deployments_bash:
    container_name: test_deployments_bash
    build:
      context: .
    working_dir: /extension
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - .:/extension
      - node_modules:/extension/node_modules
    env_file:
      - .test_deployments_dev.env

  test_deployments_test:
    container_name: test_deployments_test
    build:
      context: .
    working_dir: /extension
    command: extension-test
    volumes:
      - .:/extension
      - node_modules:/extension/node_modules
    env_file:
      - .test_deployments_dev.env
